import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/app/ui/header';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'WhoamI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} mx-auto  mt-4 max-w-2xl antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
